### ISSUE TITLE
Developers should be able to use Delaford discord [Update README]

### ISSUE THREAD

**Issue by aleks-rope** [delaford/game#116]
The Delaford discord link is expired in the README.md file. Is it possible to update the readme with the new link?
I have some basic questions regarding this project and would prefer to ask over discord(or other channels of communication) before creating these issues.

I have tried contacting the owner via email at hello@delaford.com but seems the the email isn't valid.

**Comment by naknode** [comment]
@aleks-rope I am able to click and get the invite link just fine. Does this work? https://discord.gg/nkZnHvD

**Comment by aleks-rope** [comment]
@naknode Works like a charm! Thank you! Also I just notice one minor issue on the `README.md`. There is this spelling mistake currently:

> You cna help fix that.
