### ISSUE TITLE
Trading/Banking on NPC while ON TOP causes delay

### ISSUE THREAD

**Issue by naknode** [delaford/game#119]
**What is the current behavior?**

When you are on top of an NPC and want to trade/shop/bank with them. The popup screen will not popup UNTIL you move and FINISH its progress.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

- Step on top of an NPC
- Perform action with said NPC
- Click anywhere else on Map
- Observe popup screen appears after stepping onto last tile

**What is the expected behavior?**

For the popup box to appear after performing action

**Comment by riiniii** [comment]
can i take this?

**Comment by naknode** [comment]
Of course

**Comment by naknode** [comment]
> can i take this? 

@riiniii Yes
