### ISSUE TITLE
error:'The game server is down.Please check the website for more information.'

### ISSUE THREAD

**Issue by xixi36500** [delaford/game#124]
**What is the current behavior?**
My project was deployed in a container, and the port was mapped to port 8080 of the host, which is accessed using a browser: http://localhost:8080, can be accessed normally, but constantly refreshed, and the page shows: The game server is down.Please check the website for more information.' I do n' t know why, how to check, I'm not familiar with nodejs

**If the current behavior is a bug, please provide the exact steps to reproduce.**
I follow the document as follows:
1. docker run --name game -di -p 8080：8080-v D：/workspace/game：/game node：15.5.0
2. docker exec -it game bash
3. cd /game
4. pm install
5. npm serve
6. browser access: http://localhost:8080/

**What is the expected behavior?**
Normal display, normal login

**Comment by naknode** [comment]
Hi there,

I don't have _too_ much experience with Docker but anyway, this game requires a server to run locally.

Make sure you're on a terminal where delaford and on the project root... do "node run dev:node" to run the game server.. then if you refresh the page, you''ll see the login screen.
