### ISSUE TITLE
it kicks me out of the game

### ISSUE THREAD

**Issue by Iamdevdonut** [delaford/game#131]
**laggy**

**negative.**

**to show a privacy error**

**Additional context**
I can't join and it won't let me join.
![scrnli_22_05_2021_19-16-14](https://user-images.githubusercontent.com/84630929/119237034-aa9b5e80-bb32-11eb-944d-21b900ccb59d.png) 
 
please help

**Comment by naknode** [comment]
The server is offline. There's really nothing "online" and "playable". You can download the game, install it locally and play it.
