### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by mteam88** [delaford/game#137]
full error code here: https://gist.github.com/mteam88/f7569741c16b76ea14ed1be5a1b96e86
running on bash terminal on replit.com

**Comment by naknode** [comment]
@mteam88 What node version are you using? Try updating to latest stable which is v14.x.x

**Comment by AbraaoAlves** [comment]
Sorry @naknode actua package.json expected [node version ">=10.3.0 <11"](https://github.com/delaford/game/blob/master/package.json#L6)

<img width="942" alt="image" src="https://user-images.githubusercontent.com/608731/142948858-fc724d47-7abf-4064-91ac-bb026b7f7f90.png">

**Comment by naknode** [comment]
@AbraaoAlves Update the package.json's node.js engine and try again.
