### ISSUE TITLE
Game website down

### ISSUE THREAD

**Issue by mteam88** [delaford/game#138]

**Comment by mteam88** [comment]
![Screenshot 2021-09-08 10 15 59 AM](https://user-images.githubusercontent.com/84196639/132526241-75643308-3355-49d8-92c1-8b8e35f85bb2.png)
![Screenshot 2021-09-08 10 09 10 AM](https://user-images.githubusercontent.com/84196639/132526254-fb2c5a9b-9e20-4c59-a9d3-5baadd90c7a8.png)
Obviously, there is something wrong with the game server... Not sure how to get around this...

**Comment by naknode** [comment]
Hey, I have taken the website down. Apologies for inconvienance. Not many people were using it to justify the monthly charge.
