### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by YourLocalBeanDealer** [delaford/game#155]
**What is the current behavior?**
I am unable to login with my username/password. I also cannot use the guest login.
**If the current behavior is a bug, please provide the exact steps to reproduce.**
I go into Delaford, right? Unclick Guest Login, enter my username/password. It says I entered something wrong when I click Login. I use Googles 'Saved Passwords' thing, and that doesn't work either.
**What is the expected behavior?**
I'd expect to be able to login. I'm not.
**Additional context**
Guest Login is also useless.
![Screenshot 2022-01-28 10 59 42 AM](https://user-images.githubusercontent.com/98416586/151590266-f2f8d1ad-33d4-43c3-819d-b7c6ac674611.png)

**Comment by naknode** [comment]
Hmm. Interesting. Somehow the droppedItems variable on the world map has a map ID of `281` when it should be a string thus causing the getItemData function to look for a number which doesn't exist thus giving no `graphics` to reference and causing the error.

Will try to reset the server to see if it fixes it.

**Comment by naknode** [comment]
Looks like resetting the server did the trick and there's a bug when logging off with the guest account. 

You should be able to login now.

**Comment by anbraten** [comment]
I am only getting the following error if trying to login:

```log
map.js:259 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'graphics')
    at a (map.js:259:22)
    at G.<anonymous> (map.js:274:9)
    at Array.forEach (<anonymous>)
    at G.drawItems (map.js:248:17)
    at qt.paintCanvas (engine.js:90:19)
    at qt.loop (engine.js:69:10)
    at qt.start (engine.js:79:10)
    at Delaford.vue:218:1
    at Generator.next (<anonymous>)
    at r (asyncToGenerator.js:3:20)
```

**Comment by mteam88** [comment]
Trying to log in with guest, no response when clicking login. May be related.

**Comment by naknode** [comment]
OK. There seems to be a bug then. Verified.

```javascript
    const nearbyItems = this.droppedItems.filter((item) => {
      const foundItems = (this.player.x <= (8 + item.x))
        && (this.player.x >= (item.x - 8))
        && (this.player.y <= (6 + item.y))
        && (this.player.y >= (item.y - 6));

      return foundItems;
    });
```

Somehow `world.droppedItems`'s array is getting an object that has an `id` of `281` which is wrong because it is looking for `strings` and not `numbers`. That's the issue.

`281` refers to, perhaps, the Copper/Tin rock. But how is the world.droppedItem's array getting it?

**Comment by YourLocalBeanDealer** [comment]
Just tried it and it works now. Thanks!

**Comment by InvertedBeans** [comment]
Mine just wont give me any message when i log in,just registered, help pls? i cant use the inspect element to fix so help if u can pls

**Comment by huix11** [comment]
👍

**Comment by xxhh1112** [comment]
e
