### ISSUE TITLE
npm ERROR says version not compatible

### ISSUE THREAD

**Issue by Steven-Jim** [delaford/game#205]
**What is the current behavior?**
the game won't open

**If the current behavior is a bug, please provide the exact steps to reproduce.**
go to my cloned fork of game
open powershell
type 'npm install'
wait a while
ERROR

**What is the expected behavior?**
well, as you can see, npm reported uncompatible error

**Additional context**
this is what happeend.

PS D:\Github-Mine\game> npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
[##################] \ idealTree:inflate:node_modules/isbinaryfile: sill inflate node_modules/isbinaryfile              npm notice
npm notice New minor version of npm available! 9.5.0 -> 9.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.0
npm notice Run npm install -g npm@9.6.0 to update!
npm notice
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: delaford@0.1.0
npm ERR! notsup Not compatible with your version of node/npm: delaford@0.1.0
npm ERR! notsup Required: {"node":"~10.24.1","npm":"~6.14.4"}
npm ERR! notsup Actual:   {"npm":"9.5.0","node":"v18.14.2"}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wuhongyu\AppData\Local\npm-cache\_logs\2023-03-05T04_05_02_825Z-debug-0.log

**Comment by juniorfr** [comment]
Same here

**Comment by Steven-Jim** [comment]
really anooying, because i took a LONG time setting up because i'm a beginner, but i mean really, i didn't just excepted a message syaing there's an error.....


i live in China and due to the GFW i spend half an hour during the setup of npm but....


well can anybody fix this???


---- Replied Message ----
| From | Júnior ***@***.***> |
| Date | 3/24/2023 05:07 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [delaford/game] npm ERROR says version not compatible (Issue #205) |

Same here

**Comment by SaintBert** [comment]
install then Use NVM (Node version manager.)  https://github.com/nvm-sh/nvm
then use following commands.
"nvm install 10.24.1"
"nvm use 10.24.1 "
Re run npm install.

Same thing occured to me you just need to use a specific node version and nvm makes it easy to keep track.

**Comment by Steven-Jim** [comment]
o 
thanks!
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/7/2023 22:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [delaford/game] npm ERROR says version not compatible (Issue #205) |

install then Use NVM (Node version manager.) https://github.com/nvm-sh/nvm
then use following commands.
"nvm install 10.24.1"
"nvm use 10.24.1 "
Re run npm install.

Same thing occured to me you just need to use a specific node version and nvm makes it easy to keep track.

**Comment by huix11** [comment]
same here

**Comment by xxhh1112** [comment]
eee

**Comment by xxhh1112** [comment]
e
