### ISSUE TITLE
Chat log does not clear upon re-login

### ISSUE THREAD

**Issue by naknode** [delaford/game#46]
**What is the current behavior?**

Examine the world, items or do other stuff. When you logout, and then login again, the chat stays the same.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

1. Examine an object or NPC.
2. Verify the text in the chatbox.
3. Logout.
4. Login.
5. Verify the same text still in the chatbox.

**What is the expected behavior?**

To clear the chatbox every time upon logout.

When you log back in, it should just say `Welcome to Delaford.`

**Additional context**

**Comment by omegacoo** [comment]
I can't figure out why `this.chatbox` can be spread here, but nowhere else outside this function.
Do you understand why? loc: Chatbox.vue line 109
`    appendChat(type = 'chat', username = null) {
      const typed = [
        ...this.chatbox,
        {
          type,
          color: '#1D56F2',
          text: this.said,
          username,
        },
      ];`

**Comment by omegacoo** [comment]
Eh, maybe not.
