### ISSUE TITLE
Can pick up items twice

### ISSUE THREAD

**Issue by ankush981** [delaford/game#62]
**What is the current behavior?**

**If the current behavior is a bug, please provide the exact steps to reproduce.**
- Log in as a guest
- Pick up the shield
- Move away from the current screen completely
- Come back, and the items (including the shield) are still there
- Pick up shield again
- Shield shows up in inventory

[![delaford.png](https://i.postimg.cc/05VhXdJw/delaford.png)](https://postimg.cc/Hj7SVMzY)

**What is the expected behavior?**
The shield on the ground should disappear once picked up
or
The menu should say "You already have the shield"
. . . unless this behavior is related to gameplay

**Additional context**
I was logged in as a guest, so maybe it affects gusts only (unlikely, though)? :thinking:

**Comment by naknode** [comment]
Thanks for the report! This isn't good. It doesn't matter whether you are guest or not as that only loads an object from the game. You can submit a PR to fix this high-priority bug.

**Comment by naknode** [comment]
Oh, dear me. I just re-read it.

So, what you picked up is a respawn item, I believe. Please look in `server/core/data/respawn/armor.js` and change that around and see if that's the same item.

I'll have to add documentation on the items and I will once I finish the stackable items that I have a remote branch on this repository.

**Comment by naknode** [comment]
Closing this as I believe this is the respawn item and I have not been able to reproduce this.
