### ISSUE TITLE
Dropping stackable items on map does not work

### ISSUE THREAD

**Issue by naknode** [delaford/game#69]
**What is the current behavior?**

Drop a set of 10 coins on map. You will see ONE coin graphic and when you pick it up... no quantity.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

1. Go to bank.
2. Withdraw 10 coins.
3. Drop on map
4. Observe map drop graphic is incorrect
5. Pick up coins. Observe no quantity anymore.

**What is the expected behavior?**

Show the correct graphic for quantity stated and when you pick up, have that same quantity on the item. 

**Additional context**

This really isn't a bug... more of like: I didn't get time to add this in but if you wanna take a stab! :P

**Comment by omegacoo** [comment]
Really interesting bug. If you pick up the single gold piece, the game no longer knows how much gold you have and lets you buy anything.

**Comment by naknode** [comment]
@omegacoo Indeed. The bug is very easy to spot mainly because we don't take into account quantities of dropped items and thus it looks like 1 coin. 

Should be an easy fix.

**Comment by Jaace** [comment]
I'd be happy to try to take a look into this
