### ISSUE TITLE
Settings updates

### ISSUE THREAD

**Issue by erezvish** [delaford/game#71]
I'd like to push two minor changes regarding settings if that's alright:

1.  a script for package.json for globally installed nodemon: 
` "dev:node_global": "set NODE_ENV=development && nodemon --exec ./node_modules/.bin/babel-node --no-babelrc server.js --presets @babel/preset-env --plugins @babel/plugin-transform-modules-commonjs"`
2. add '*.history' to gitignore. This should ignore the history directory, which I use for local history.  

If you approve this issue I'll add and push the commit.

Thanks

**Comment by naknode** [comment]
1. Not everyone will have nodemon globally installed so this helps us control their version and make it installed.

2. Sounds good to me

**Comment by erezvish** [comment]
So push only the history? The nodemon locall script doesn't work for me for some reason so I'll just have to work around it.

**Comment by naknode** [comment]
Nodemon is set in package.json as a devDep. What error are you getting? It should be installed locally. But I also know that running NPM scripts via folders is different in different OSes and I do believe there are scripts to help with that...

**Comment by erezvish** [comment]
that's what I'm getting. I tried solving it before then ended up with just using the global installation. 
I'll try and look it up later, it's probably a silly issue
 
 set NODE_ENV=development && ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node --no-babelrc server.js --presets @babel/preset-env --plugins @babel/plugin-transform-modules-commonjs

**'.' is not recognized as an internal or external command,**
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! delaford@0.1.0 dev:node: `set NODE_ENV=development && ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node --no-babelrc server.js --presets @babel/preset-env --plugins @babel/plugin-transform-modules-commonjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the delaford@0.1.0 dev:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\home\AppData\Roaming\npm-cache\_logs\2019-03-01T18_04_20_342Z-debug.log

**Comment by naknode** [comment]
Ah, yes. That's where you have to flip it around to adhere to Window's
standards. So, that being said, there has to be an NPM script that will
allow the execution of local NPM scripts from the CLI in any OS (windows,
os, linux,etc.) and have it work 100% of the time.  I just haven't found it
yet because I never had a reason too (and now it seems like I do) :-)
