### ISSUE TITLE
No skill stats showing in pane & console TypeError 

### ISSUE THREAD

**Issue by erezvish** [delaford/game#74]
**What is the current behavior?**
1. Console error: 
> TypeError: string.charAt is not a function at VueComponent.capitalizeFirstLetter
2. Stats tab is not showing skills

**If the current behavior is a bug, please provide the exact steps to reproduce.**
1. login into the game (I'm using the guest login)
2. open the console
3. observe the error
*if the error doesn't appear try moving the player around a bit

**What is the expected behavior?**
1. No error
2. When clicking the stats tab in the right pane, observe a list of skills

**Additional context**
This error seems to be due to the behavior of the v-for in Stats.vue . My Vue is a little rusty, but I believe the syntax used is suitable for working with object properties, whereas the stats are received as an array.
This results in capitalizeFirstLetter method getting the number 0 and failing.

To fix the issue, the v-for should probably be on skill in skills and the capitalizeFirstLetter method should receive skill.name
*capitalizeFirstLetter should protect itself by addressing cases where non string input is received is not a string. Alternatively we can replace it with css text-transform: capitalize.

@naknode 
I'm opening new issues for new things I encounter if I'm submitting a pull request shortly after. I think I read somewhere that pull requests will only be accepted for issues, and even if not, I thought it's a good such things documented. Please let me know if you want me to keep doing that or just submit a pull request.

**Comment by naknode** [comment]
@erezvish Yes, it's good that we document via Issues so this is a good way to go about it. But I believe it should be a your discretion.

For example, prominent issues or feature requests should always be documented. Small UI fixes and errors can just have PRs and no issues needed.
