### ISSUE TITLE
Mouse allows to walk on blocked tiles after path lands mouse on a blocked tile

### ISSUE THREAD

**Issue by naknode** [delaford/game#8]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When you right-click to walk somewhere, your mouse will still show "yellow" when the path finishes and your mouse is hovering on a blocked tile.

![mouse_wall_issue](https://user-images.githubusercontent.com/616320/34597336-a9cd64d4-f1ab-11e7-9b51-e5f7936e886a.gif)

**If the current behavior is a bug, please provide the exact steps to reproduce.**

Make sure that your mouse will land on a blocked tile when player is finished walking.

1. Right-click on a walkable tile
2. Click on 'Walk here'

**What is the expected behavior?**

For the mouse selection to turn red and thus not click be attempt to walk there.

**Comment by naknode** [comment]
Note: this bug is likely not to be reproduced many times. As soon as you move your mouse at least ONE pixel after you click, then the issue will be fixed.

But, still, it's still nice to have this fixed.

**Comment by dathappysheep** [comment]
I can reproduce, assign me to the question, please!

**Comment by naknode** [comment]
@dathappysheep You can fork at any time and send in a PR :-)

**Comment by naknode** [comment]
@maxrumsey I cannot assign this issue to you if you are not a member of this organization.
