### ISSUE TITLE
Double-clicking a queueable action item puts it in queue more than once

### ISSUE THREAD

**Issue by naknode** [delaford/game#85]
**What is the current behavior?**

You hover over an item on the ground. Double or triple click really fast to "Take" the item. Observe your multiple of items.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

See above.

**What is the expected behavior?**

Only allow once.

**Additional context**

Should be really easy to fix.

**Comment by erickcelio** [comment]
I can catch that issue?

**Comment by erickcelio** [comment]
I can't reproduce that when I click two times or more in an item the server just crashes I made a fix for that and create that issue #106 and pr #107, have any other way to reproduce that?

**Comment by naknode** [comment]
Works as intended. However the image on the ground (for coins ,example) does not reflect the same image dropped from the inventory. 

ie: you drop 100,000 coins, and you see 1 coin graphic. We can get to that in another issue.
