### ISSUE TITLE
Modularize import statements

### ISSUE THREAD

**Issue by naknode** [delaford/game#87]
**What mechanics does this feature affect?**

code only

**How hard would it be to implement this feature on a scale of 1-10 (10 = hardest)?**

1. Just a bit of work.

**What is the feature request?**

Using an npm package like `link-module-alias` or similar, to replace all of the `import` or `require` statements with proper module aliases.

Right now, we have import statements like `import EXAMPLE from '../../../../`, you get the idea. With this change, it would be `import EXAMPLE from '@server/test.js`.

**Comment by ccrosario** [comment]
Mind if I take a stab at this?

**Comment by naknode** [comment]
@ccrosario Go right ahead! Should be pretty straight forward.

**Comment by erickcelio** [comment]
I will do some work on that
