### ISSUE TITLE
Can you make your guide more specific?

### ISSUE THREAD

**Issue by MasterSIO** [delaford/game#91]
I can't seem to figure out what I need to do in order to play this game/ host a server. It would would be helpful I could know the following: What software I need to download in order to do this, and what to do with that software. If there is any software to download. It's just really confusing, and I would like to play.

**Comment by naknode** [comment]
Go to your terminal.

Type these instructions:

```
git clone git@github.com:YOUR_USERNAME/game.git
cd game
npm install
npm run serve
```

Go to whatever url `npm run serve` tells you. Make sure to select `Guest Account` and you should be good to go.

**Comment by MasterSIO** [comment]
I'm using a Mac, so terminal for me can have a few meanings. One, you want
me to download something or two you literally mean my terminal that my
MacBook comes with.

**Comment by naknode** [comment]
You can use whatever you'd like. Terminal on your Mac is fine and will work.

**Comment by MasterSIO** [comment]
Thanks! This was very helpful. It works now. 😀

**Comment by naknode** [comment]
Glad to hear it. Have fun!
