### ISSUE TITLE
Popup screen does not close when moving away

### ISSUE THREAD

**Issue by naknode** [delaford/game#94]
**What is the current behavior?**

When you open a popup screen, usually via trading, and you click someone on the edge of the canvas to go somewhere on the map, the popup screen stays connected.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

1. Trade a vendor.
2. Confirm screen is visible.
3. Click on edge of canvas to go somewhere in map.
4. Confirm the trade screen is still up.

**What is the expected behavior?**

When you move somewhere on the map, the online screen should close for an easier UX experience and viability of bug abuse.

**Comment by brainfart-be** [comment]
I'm taking a quick look and see if i can fix this.
