### ISSUE TITLE
You can sell gold to (general) stores

### ISSUE THREAD

**Issue by naknode** [delaford/game#95]
**What is the current behavior?**

You can sell gold to stores.

**If the current behavior is a bug, please provide the exact steps to reproduce.**

1. Have gold.
2. Go to general trade vendor and start a trade.
3. Sell gold (any quantity).
4. Confirm store received purchase.

**What is the expected behavior?**

You should be blocked from selling gold and see on your screen "You cannot sell gold." or something like that.

**Additional context**

This should be really easy. You can declare a server-side array `[]` that includes `prohibitedItemsToSell` and add the `gold` as the first one. Later on, we can include quest items.

A good place to start this PR would be in the file `server/player/handlers/actions/index.js` in the `player:screen:npc:trade:action` method where the server starts the trade transaction.

**Comment by srichter** [comment]
I see that there's the attribute of `untradeable` defined on the Coins item already, would this be a good way to handle defining prohibited items? That way the array does not need to be updated and we can just check the attribute on the item itself.

**Comment by naknode** [comment]
@srichter Yep, that sounds like a good idea. Maybe rename that to `prohibited` or some such to give better code clarity as it will serve the same function in trades as well as buying/selling. And if you have too, which I think you will, move the function to a util file and import as needed. Should be really easy.

**Comment by srichter** [comment]
Didn't see the need for a separate file since there was already checking there for specialized shops. Should we prevent the player from even having the option of selling their coins by not showing the context menu items for selling if an item is prohibited?

**Comment by naknode** [comment]
Makes sense. And we should. It makes the flow of the UI flow better.

If you can't tell, we are mimicing a lot of RuneScape Classic game mechanics.
