### ISSUE TITLE
The value of coins to a shop is false

### ISSUE THREAD

**Issue by srichter** [delaford/game#99]
**What is the current behavior?**
When you value coins in your inventory the value is said to be false.

**If the current behavior is a bug, please provide the exact steps to reproduce.**
1. Have coins in your inventory
2. Start a trade with a store
3. Open the context menu on coins
3. Select "Value Coins"
4. The chatbox shows "Coins: false coins."

**What is the expected behavior?**
The game should either return the exact amount of coins already in the inventory or, even better, something such as "priceless" which would also work for quest items.

**Additional context**
Would it instead be better to not show the option to value coins? The player may desire to value quest items which would also have no value, so maybe it would be better to return "Priceless" or something similarly in-lore for prohibited items.

**Comment by naknode** [comment]
I think a witty line would work well. I do believe there a plans to fully get the quantity of coins when you examine them though
